### ISSUE TITLE
Serveur HTTP

### ISSUE THREAD

**Issue by b0ogieMan** [dil-classroom/projet-bijelic_coke_mbayo_salhi#53]
# Task Template
## Description 
En tant qu’utilisateur, j’aimerai exécuter la commande suivante de manière à pouvoir visualiser le résultat de la
compilation du site Internet dans un navigateur Web.
$ statique serve /mon/site

### Sous-tâches
- [ ] Ajouter Javalin à la configuration Maven
- [ ] Initialiser un serveur web
- [ ] Implémenter la fonction serve de picocli
- [ ] (Trouver un moyen de générer automatiquement les GET pour chaque fichier HTML)

### Optimiste

| **Nombre d'heures** | - |
|-----------------------------|---|

### Pessimiste 

| **Nombre d'heures** | - |
|-----------------------------|---|

### Attendu 

| **Nombre d'heures** | - |
|-----------------------------|---|

### Temps pris en pratique

| **Nombre d'heures** | - |
|-----------------------------|---|

# Liens utiles
- [Lien 1]()
- [Lien 2]()
- [Lien 3]()
