### ISSUE TITLE
Javadoc

### ISSUE THREAD

**Issue by b0ogieMan** [dil-classroom/projet-bijelic_coke_mbayo_salhi#84]
# Task Template
## Description 

En tant que développeur, 
je veux configurer Maven
pour que je puisse publier une javadoc au format HTML et l'ajouter à la release.

### Sous-tâches
- [ ] Ajouter le plugin javadoc à Maven
- [ ] Configurer le plugin pour publier au format HTML
- [ ] Ajouter la Javadoc à la release

### Optimiste

| **Nombre d'heures** | - |
|-----------------------------|---|

### Pessimiste 

| **Nombre d'heures** | - |
|-----------------------------|---|

### Attendu 

| **Nombre d'heures** | - |
|-----------------------------|---|

### Temps pris en pratique

| **Nombre d'heures** | - |
|-----------------------------|---|

# Liens utiles
- [Lien 1]()
- [Lien 2]()
- [Lien 3]()
